# Generated by Django 6.0.4 on 2026-04-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('cod_usu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cafeteria.usuario')),
            ],
        ),
    ]
